site_name: GÃ¦rneArnes nettverksskole

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

nav:
  - Hjem: index.md
  - Oppsett:
      - Oppsett av PC: dev-environment.md
      - Vedlikehold av Docker: docker-vedlikehold.md
  - Ansible:
      - Hemligheter i Ansible: ansible-vault-guide.md
  - Git:
      - Git grunnleggende: git-basics.md
      - Github Actions: github-actions-deploy.md
      - Pre-commit: pre-commit-guide.md
      - Conventional Commits: conventional-commits.md
      - GitHub Branch Protection: github-branch-protection.md
  - Sikkerhets betraktninger:
      - Kritiske punkter: CRITICAL-FIXES.md
      - Security assessment: security-assessment.md
