site_name: GærneArnes nettverksskole
site_description: Dokumentasjon for oppsett og vedlikehold av utviklingsmiljø
site_author: Arne Opdal
site_url: https://www.ao-test.net/dev-setup/
copyright: '© 2025 Arne Opdal'


repo_name: aopdal/dev-setup
repo_url: https://github.com/aopdal/dev-setup

theme:
  name: material
  palette:
    # Palette toggle for light mode
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Bytt til mørk modus
    # Palette toggle for dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Bytt til lys modus
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.expand
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

markdown_extensions:
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format

nav:
  - Hjem: index.md
  - Oppsett:
      - Oppsett av PC: dev-environment.md
      - Vedlikehold av Docker: docker-vedlikehold.md
  - Ansible:
      - Hemligheter i Ansible: ansible-vault-guide.md
  - Git:
      - Git grunnleggende: git-basics.md
      - Git Workflows (Fork & Branch): git-workflows.md
      - Github Actions: github-actions-deploy.md
      - Pre-commit: pre-commit-guide.md
      - Conventional Commits: conventional-commits.md
      - GitHub Branch Protection: github-branch-protection.md
  - Sikkerhets betraktninger:
      - Security assessment: security-assessment.md
